Vagrant.configure("2") do |config|
  config.vm.box = "mitchellh/boot2docker"
  config.vm.provider "virtualbox" do |v|
    # On VirtualBox, we don't have guest additions or a functional vboxsf
    # in TinyCore Linux, so tell Vagrant that so it can be smarter.
    v.check_guest_additions = false
    v.functional_vboxsf     = false
  end

  ["vmware_fusion", "vmware_workstation"].each do |vmware|
    config.vm.provider vmware do |v|
      if v.respond_to?(:functional_hgfs=)
        v.functional_hgfs = false
      end
    end
  end

  # b2d doesn't support NFS
  config.nfs.functional = false
  config.vm.network :private_network, ip: '192.168.50.1'
  config.vm.network :forwarded_port, guest: 4243, host: 4243
  (49000..49900).each do |i|
    config.vm.network :forwarded_port, guest: i, host: i
  end
  #config.vm.network :forwarded_port, guest: 80, host: 8080
  #config.vm.network :forwarded_port, guest: 3306, host: 3306
end


